USER_STATUS_ACTIVE = 100
USER_STATUS_DELETED = -100
USER_STATUS_DISABLED = -50 
USER_SALT_LENGTH = 10 

USER_MAX_LOGIN_ATTEMPTS_BEFORE_CAPCHA = 3 
USER_MAX_LOGIN_ATTEMPTS_BEFORE_DISABLED = 10

USERNAME_REGEXP_PATTERN = "^[0-9a-zA-Z_-]{3,100}$"

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 255
PASSWORD_MIN_CAPITAL_LETTERS = 1
PASSWORD_MIN_NUMBERS = 1